spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pennywise
    username: root
    password: dlrkdhsoff

  jwt:
    secret:
      key: KU1MrpjZAhmPgnD6pfZ6pVFfOFL8yVuQ7/rQDki/iVkzesH8782X9s656q1txnhzkg1I40ovzcpgXCUHD40/qQ==

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

  data:
    redis:
      port: 6379
      host: localhost
      timeout: 1000
